library(Seurat)
library(dplyr)
library(Matrix)
library(googledrive)
mm.data <- Read10X(data.dir = "/Users/kylajenkins/Downloads/raw_gene_bc_matrices/mm10")

mice_obj <- CreateSeuratObject(counts = mm.data, min.cells = 3, min.genes = 200, project = "mm")

head(mice_obj@meta.data)
mm.data[, 1:30]
barplot(rowSums(mm.data))
rowMeans(mm.data)
barplot(rowSums(mm.data[1:50,]))
barplot(rowSums(mm.data[51:100,]))
barplot(rowSums(mm.data[101:150,]))
barplot(rowSums(mm.data[151:200,]))
barplot(rowSums(mm.data[201:250,]))
nrow(mm.data)
ncol(mm.data)
barplot(rowMeans(mm.data[1:10,]))
barplot(rowMeans(mm.data[11:20,]))
barplot(rowMeans(mm.data[21:30,]))
barplot(rowMeans(mm.data[31:40,]))
barplot(rowMeans(mm.data[41:50,]))
